[package]
name = "bur"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2018"


[features]
default = ["idena", "binance", "cpu_usage"]

idena = ["idena_api", "serde_json"]
binance = ["tokio-binance", "tokio/time", "serde_json"]
cpu_usage = ["psutil/cpu"]

[dependencies]
idena_api = { path = "../idena_api", optional = true }  # { git = "https://github.com/eggmund/idena_api" }
tokio-binance = { version = "0.4", optional = true }
serde_json = { version = "1.0", optional = true }
psutil = { version = "3.1.0", default-features = false, features = ["cpu"], optional = true }

chrono = "0.4"
tokio = { version = "0.2", features = ["macros"] }
async-trait = "0.1"
log = "0.4"
pretty_env_logger = "0.4"

