[package]
name = "bur"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
idena_api = { git = "https://github.com/eggmund/idena_api" }
binance = "0.10.4"

chrono = "0.4"
tokio = { version = "0.2", features = ["macros"] }
async-trait = "0.1"
log = "0.4"
pretty_env_logger = "0.4"